#!/bin/bash
source "$(brew --prefix)/libexec/commit.sh"
source "$(brew --prefix)/libexec/scope.sh"
source "$(brew --prefix)/libexec/issue.sh"
source "$(brew --prefix)/libexec/error.sh"

main() {
    get_commit_type
    ask_for_scope
    while true; do
        read -e -r -p "Enter your commit message: " MESSAGE
        if [[ -z "$MESSAGE" ]]; then
            print_error "A commit message is required. Please enter a message."
        else
            MESSAGE=$(echo "$MESSAGE" | tr '[:upper:]' '[:lower:]')
            break
        fi
    done

    ask_for_issue
    COMMIT_MESSAGE="$EMOJI$TYPE$SCOPE: $MESSAGE$ISSUE_REF"
    echo "Your commit message: $COMMIT_MESSAGE"
    git commit -m "$COMMIT_MESSAGE"
}

main